settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: go-react
  path: ./cmd
  commands:
    run:
      status: true
    generate:
      status: false
  watcher:
    extensions:
    - go
    paths:
    - ../../
    ignored_paths:
    - .git
    - .realize
    - vendor
